### ISSUE TITLE
Docker eosiocpp command throwing error.

### ISSUE THREAD

**Issue by joaoritter** [EOSIO/eos#4105]
I came across [this issue](https://github.com/EOSIO/eos/issues/2387), which I think is related, but I'm still having trouble. I've got my docker containers set up and running. I've successfully created keys and accounts, and successfully completed the tutorial https://github.com/EOSIO/eos/wiki/Tutorial-eosio-token-Contract and am now working on https://github.com/EOSIO/eos/wiki/Tutorial-Hello-World-Contract.
I've set the following alias "alias eosiocpp='docker-compose exec keosd /opt/eosio/bin/eosiocpp'", but when I run "eosiocpp -o hello.wast hello.cpp", I get "clang-4.0: error: no such file or directory: 'hello.cpp'"
I am sure I'm running from the correct directory. I'm likely misunderstanding the docs, some clarification would be great!

Thank you

**Comment by ntheile** [comment]
+1

**Comment by ntheile** [comment]
I realized the file system is actually mounted from Docker to your local file system here:  /tmp/eosio. So to get eosiocpp to actually compile the code, i created a contracts directory in /tmp/eosio/data/contracts then edited the hpp and cpp files in TextEdit. 

Next to generate the compiled code I ran this docker command:

<pre>
docker exec eosio bash -c 'cd mnt/dev/data/contracts/mycontract && eosiocpp -o mycontract.wast mycontract.cpp'
</pre>

**Comment by andriantolie** [comment]
@ntheile is correct here. @joaoritter if you are using docker, you need to pass the contract location _inside your Docker_. When you call `eosiocpp -o hello.wast hello.cpp`, it's actually looking for hello.cpp inside the root folder of your Docker which doesn't exist. You need to map your contracts to a location inside the Docker and then pass the contract location _inside your Docker_ to eosiocpp

**Comment by luckyyang** [comment]
Add the volume mapping change to your `docker-compose.yml`, then your `docker-compose.yml` would like this:

```
version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    container_name: nodeosd
    build:
      context: .
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ../contracts:/contracts

  keosd:
    container_name: keosd
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ../contracts:/contracts

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
  contracts:
    external: true
```

After the containers are running up by run `docker-compose up -d`, there will be a `contract` folder in your `nodeosd` and `keosd` container under `/` path, verify via these commands:
```shell
docker exec -it keosd pwd
docker exec -it keosd ls
docker exec -it keosd ls contracts
```
Then you will know where you are and what you have.

Every time you want to reference the contract file inside contracts folder you need to specify the path of the contract file, for example:
```shell
eosiocpp -o /contracts/hello/hello.wast /contracts/hello/hello.cpp
```

P.S. If you want to run eos command anywhere then use these alias (add them to your `.bashrc` and do not forget to change the path):
```shell
alias cleos='docker-compose -f DIR-TO-YOUR-EOS-FOLDER/Docker/docker-compose.yml exec nodeosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://localhost:8900'

alias eosiocpp='docker-compose -f DIR-TO-YOUR-EOS-FOLDER/eos/Docker/docker-compose.yml exec nodeosd /opt/eosio/bin/eosiocpp'
```
