### ISSUE TITLE
Setting up environment with docker

### ISSUE THREAD

**Issue by jpopesculian** [EOSIO/eos#5091]
I tried to follow the guide written here and encountered some problems: https://medium.com/@ekkis/eos-development-on-docker-3f4eb9b680ec

On Ubuntu 18.04. Steps taken

Setup folders

```bash
mkdir eos && cd eos
mkdir contracts
```

Create `docker-compose.yml`

```yaml
version: "3"

services:
  nodeosd:
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: eosio/eos-dev
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./contracts:/contracts/usr
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
  keosd-data-volume:
```

So your filesystem looks like:

```
eos/
  docker-compose.yml
  contracts/
```

Run docker compose:

```bash
docker-compose up -d
```

Alias `eosiocpp`

```bash
eosiocpp() { d=/contracts/usr; docker exec eos_nodeosd_1 /opt/eosio/bin/eosiocpp $1 $d/$2 $d/$3; }
```

Create smart contract

```bash
mkdir contracts/hello
touch contracts/hello/hello.cpp
```

Smart contract:

```cpp
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>
using namespace eosio;

class hello : public eosio::contract {
  public:
      using contract::contract;

      /// @abi action
      void hi( account_name user ) {
         print( "Hello, ", name{user} );
      }
};

EOSIO_ABI( hello, (hi) )
```

run `eosiocpp`

```bash
eosiocpp -o hello/hello.wast hello/hello.cpp
```

output:

```
/contracts/usr/hello/hello.cpp:1:10: fatal error: 'eosiolib/eosio.hpp' file not found
#include <eosiolib/eosio.hpp>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

I don't know in which ways I should set up my environment differently. I've tried building locally (using `sudo make install` with or without aliasing commands) and in almost every situation `eosiocpp` cannot seem to find the appropriate libs. Either this error or not finding `stdint.h`. Is there any advice you could give me?

**Comment by lucca65** [comment]
I'm struggling with the same, its very hard to get all of Eos working on my Mac. Even with docker this is a frustrating experience of try and error

**Comment by zachalam** [comment]
Also running into this issue but on Ubuntu 16.04 - any guidance would be greatly appreciated.

**Comment by jpopesculian** [comment]
So I went ahead ahead and built and installed the eosio.wasmsdk toolchain, and got `eosio-cpp` working (albeit also had its complication with boost not being found) but through that toolchain as of right now I can't generate an abi. Any advice there @taokayan?

**Comment by vijaytabhatt** [comment]
i am also facing same issue ,fatal error: 'eosiolib/eosio.hpp' file not found
any solution?

**Comment by lucca65** [comment]
So I made it work using docker, and it may be helpful for you folks.

First I'm using this `docker-compose.yml` file:


```yml
version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    container_name: nodeosd
    build:
      context: .
    image: eosio/eos-dev
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ../contracts:/contracts # this is important

  keosd:
    container_name: keosd
    image: eosio/eos:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ../contracts:/contracts
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
  contracts:
    external: true
```

I'm also using those alias to be able to interact with it:

```sh
alias cleos='docker-compose -f /Users/lucca/Development/cpp/eos/Docker/docker-compose.yml exec keosd /opt/eosio/bin/cleos -u http://nodeosd:8888 --wallet-url http://localhost:8900'

alias eosiocpp='docker-compose -f /Users/lucca/Development/cpp/eos/eos/Docker/docker-compose.yml exec nodeosd /opt/eosio/bin/eosiocpp'
```

For all of that to work out I need to use a docker volume that is mapped to `CHANGE_TO_YOUR_EOS_PATH/contracts`. It must be the build variation.

Also to use `eosiocpp` you will have to use the directories from your docker:

`$ eosiocpp /contracts/hello`

It helped me a lot to do stuff inside docker so everything is liked using

`docker-compose -f ../../Docker/docker-compose.yml exec nodeosd bash`

It also took me a while to notice that we use `cleos` from the `keos` docker but we build from `nodeos` docker, so be sure to connect/use the right docker when needed

With all of this I could stop getting those `eosio.hpp file not found` errors
