### ISSUE TITLE
Error 3200004: fail to resolve host

### ISSUE THREAD

**Issue by zillerium** [EOSIO/eos#5135]
$ cleos get info
Error 3200004: fail to resolve host
Error Details:
Error resolving "nodeosd:${url}" : Host not found (non-authoritative), try again later

I added -p in the nodeos to stop another error and now I get fail to resolve host 

I am using docker. Here is the docker-compose.yml - 
```
more docker-compose.yml
version: "3"

services:
  builder:
    build:
      context: builder
    image: eosio/builder

  nodeosd:
    build:
      context: .
    image: eosio/eos
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e -p --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http
-alias=localhost:8888 --plugin eosio::chain_plugin --plugin eosio::mongo_db_plugin --plugin eosio::history_plugin  --plugin eosio::http_plug
in
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: eosio/eos
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-a
lias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
```
