### ISSUE TITLE
cleos: Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?

### ISSUE THREAD

**Issue by timohe** [EOSIO/eos#6112]
I am using:
`cleos create key --to-console`
and then 
`cleos create account initia tester [pubKey from above]`

and getting the response:

> Failed to connect to nodeos at http://127.0.0.1:8888/; is nodeos running?

But if I do `curl http://127.0.0.1:8888/v1/chain/get_info` I am getting a response, so nodeos should be running also I can see in the docker logs that it is producing blocks.

**Comment by brianjohnson5972** [comment]
did you try:
```
cleos get info
```
Just wanting to issolate if it is specific to the resource or to cleos in general

**Comment by timohe** [comment]
This is the get info output:
```
{
  "server_version": "f9a3d023",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 13088,
  "last_irreversible_block_num": 13087,
  "last_irreversible_block_id": "0000331fc906b6818bbef1376a447ed547e69af097293f2acfc83cfddc00c63f",
  "head_block_id": "00003320a17b5e64ccab3c658470c20eef7a7d6bfacaef6b4e22d346a3ea954d",
  "head_block_time": "2018-10-23T18:12:45.000",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 200000000,
  "virtual_block_net_limit": 1048576000,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576,
  "server_version_string": "v1.4.1"
}
```
Now that I tried again I am getting: 

> Failed to connect to keosd at http://172.19.0.2:9876; is keosd running?

I also tried now with a dockerfile like this:
```
version: "3"

services:
  nodeosd:
    image: eosio/eos:latest
    #--delete-all-blocks is to recover after unexpected docker shutdown
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888 --delete-all-blocks
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m  

  keosd:
    image: eosio/eos:latest
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=localhost:8900 --http-alias=keosd:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m  

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
```
Which worked (also worked when built from source). So maybe some issue with the manually created network, while with docker-compose the default is used.
