### ISSUE TITLE
cleos get info response slowly

### ISSUE THREAD

**Issue by garden2weini** [EOSIO/eos#9998]
I have added option(by docker-compose)
      - --wasm-runtime=eos-vm-jit
      - --eos-vm-oc-enable
but a day after restart, cleos get info still response slowly.
btw: eosio version is 2.0.7

**Comment by garden2weini** [comment]
docker-compose.yml
```yaml
version: '3'
services:
  eosio:
    image: ...eos:2.0.7
    container_name: eosio
    stop_signal: SIGUSR1
    stop_grace_period: 30m
    restart: always
    network_mode: host
    command:
      - nodeos 
      - --data-dir=/data
      - --chain-state-db-size-mb=655360
      - --wasm-runtime=eos-vm-jit
      - --eos-vm-oc-enable
      - --genesis-json=/genesis.json
      - --plugin=eosio::chain_api_plugin 
      - --plugin=eosio::net_api_plugin 
      - --plugin=eosio::http_plugin
      - --plugin=eosio::history_api_plugin
#      - --plugin=eosio::history_plugin
      - --plugin=eosio::state_history_plugin
      - --state-history-endpoint=0.0.0.0:8080
      - --trace-history
      - --chain-state-history
      - --disable-replay-opts
      - --filter-on=*
      - --p2p-peer-address=peer.main.alohaeos.com:9876
      - --p2p-peer-address=eosbp-0.atticlab.net:9876
      - --p2p-peer-address=api.binance-eos.com:9875
      - --p2p-peer-address=p2p.eosio.cr:9876
      - --p2p-peer-address=eos.csx.io:9876
      - ...
```
